# Generated by Django 5.2.6 on 2025-09-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sepatu', 'Sepatu'), ('bola', 'Bola'), ('jersey', 'Jersey'), ('aksesoris', 'Aksesoris')], max_length=20),
        ),
    ]
